version: "3.2"

services:
  dev:
    container_name: supra
    image: paritytech/ci-linux:974ba3ac-20201006
    working_dir: /var/www/supra
    ports:
      - "9944:9944"
    environment:
      - CARGO_HOME=/var/www/supra/.cargo
    volumes:
      - .:/var/www/supra
      - type: bind
        source: ./.local
        target: /root/.local
    command: bash -c "cargo build --release && ./target/release/supra --dev --ws-external"
